version: '3.8'

services:
  db:
    image: mysql:8.0.27
    container_name: db
    command: --authentication_policy=mysql_native_password
    restart: 'no'
    user: root
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=tribe

  app:
    image: tribe_app
    container_name: app
    restart: 'no'
    working_dir: /var/www/
    depends_on:
      - db
    volumes:
      - ./src:/var/www

  nginx:
    image: nginx:1.19-alpine
    container_name: web
    restart: 'no'
    ports:
      - "80:80"
    depends_on:
      - app
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
