FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

# configure timezone data
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y tzdata && \
    ln -fs /usr/share/zoneinfo/Asia/Kolkata /etc/localtime && \
    tzdata

# install system packages
RUN apt-get update && \
    apt-get install -y lsb-release ca-certificates apt-transport-https software-properties-common && \
    add-apt-repository ppa:ondrej/php && \
    apt-get install -y build-essential \
        vim \
        zip \
        unzip \
        p7zip-full \
        curl \
        s3cmd \
        php7.2-fpm \
        php7.2-mysqli \
        php7.2-curl \
        php7.2-cli \
        php7.2-mbstring \
        php7.2-gd \
        php7.2-zip \
        php7.2-xml \
        poppler-utils \
        python3-pip \
        imagemagick \
        ffmpeg \
        net-tools \
        nginx \
        git

# install composer
RUN curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php && \
    php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer

RUN usermod -d /tmp/www-data www-data

# set php configuration values
WORKDIR /var/www
ENV PHP_INI_DIR='/etc/php/7.2/fpm'
RUN sed -i 's/post_max_size = 8M/post_max_size = 1024M/' "${PHP_INI_DIR}/php.ini" && \
    sed -i 's/upload_max_filesize = 2M/upload_max_filesize = 1024M/' "${PHP_INI_DIR}/php.ini" && \
    sed -i 's/memory_limit = 128M/memory_limit = 2048M/' "${PHP_INI_DIR}/php.ini" && \
    sed -i "\|include /etc/nginx/sites-enabled/\*;|d" "/etc/nginx/nginx.conf"

EXPOSE 80

CMD /etc/init.d/php7.2-fpm start && service nginx start && tail --follow /var/log/nginx/access.log
